# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 851aa943ccc681fbce2c6ff6b96a006934d41a58d54986552a9bc013cb342ef353eb1215ff6949dd00a6809762d806ae46fab42bd8cafd58b2807f9796189a3b

test:
  secret_key_base: 3f86930d4e4de246f81b799b7d2877406bc5da7771c85cc6090c072e903cec01a1ff3a9e5dddee8000f15d6592fe88b19826dc4717b057a292c930e9ab3d4ad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
